<?php

if (!empty($_GET['page'])) {
    if ($_GET['page'] == 'accueil') {
        require_once 'controllers/controllerHomepage.php';
        homepage();
    }elseif ($_GET['page'] == 'articles') {
        require_once 'controllers/controllerArticles.php';
        articles();
    }elseif ($_GET['page'] == 'admin') {
        require_once 'controllers/controllerAdmin.php';
        admin();
    }/*elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }elseif (condition) {
        # code...
    }*/
    
} else {
    require_once 'controllers/controllerHomepage.php';
        homepage();
}

?>